<?php

namespace Eotvos\EjtvBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SchoolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SchoolRepository extends EntityRepository
{
    /**
     * Returns schools tarting with the given name prefix
     * 
     * @param mixed $prefix first characters of name
     * 
     * @return array results
     */
    public function getWithPrefix($prefix)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT s.id, s.omid, s.name, s.city, s.address, s.postalcode FROM Eotvos\EjtvBundle\Entity\School s WHERE s.name LIKE :prefix AND (s.eductype LIKE :educ1 OR s.eductype LIKE :educ2) ORDER BY s.name ASC')
            ->setParameter('prefix', $prefix.'%')
            ->setParameter('educ1', '%gimnázium%')
            ->setParameter('educ2', '%szakköz')
            ->getResult();
    }

}
